module.exports=[
 {
  "sales_id": "1",
  "nama_lop": "PERUMAHAN BRD RESIDENCE",
  "nama_segment": "Non APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "Bumirejo, Pekalongan Barat, Kota Pekalongan, Jawa Tengah 51117",
  "stat": "Prospect",
  "potensi_hh": "31",
  "jumlah_huni": "59",
  "developer": "PT. AJISAKA",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 1,
  "jml_odp": "3",
  "status_ftth": "Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "PERUMAHAN PISMA SERUNI ASRI",
  "nama_segment": "Non APC",
  "nama_kemitraan": "Marketing",
  "alamat": "",
  "stat": "Pra Prospect",
  "potensi_hh": "57",
  "jumlah_huni": "3",
  "developer": "PT PISMA GAJAH PUTRA",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 2,
  "jml_odp": "",
  "status_ftth": "Not_Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "PERUMAHAN GAMA ASRI PEKALONGAN",
  "nama_segment": "Non APC",
  "nama_kemitraan": "Marketing",
  "alamat": "",
  "stat": "Pra Prospect",
  "potensi_hh": "300",
  "jumlah_huni": "120",
  "developer": "",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 3,
  "jml_odp": "2",
  "status_ftth": "Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "PERUMAHAN SHAPPIRE MEDITERANIA PEKALONGAN",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Marketing",
  "alamat": "Jl Kapt Patimura Gamer Pekalongan Jawa Tengah",
  "stat": "Go Live",
  "potensi_hh": "85",
  "jumlah_huni": "12",
  "developer": "PT. MITRA SHAPPIRE SEJAHTERA",
  "nama_mitra": "Telkom Akses, PT",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 4,
  "jml_odp": "1",
  "status_ftth": "Not_Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "PERUMAHAN CITRA GARDEN",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "Jalan Kusuma Bangsa, Panjang Baru, Pekalongan Utara, Panjang Baru, Pekalongan, Kota Pekalongan, Jawa Tengah 51141",
  "stat": "Prospect",
  "potensi_hh": "86",
  "jumlah_huni": "36",
  "developer": "PT. INTAN KHARISMA JAYA",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 5,
  "jml_odp": "6",
  "status_ftth": "Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "PERUMAHAN GAIA RESIDENCE",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "Jl Slamet Riyadi Batang Jawa Tengah",
  "stat": "Prospect",
  "potensi_hh": "52",
  "jumlah_huni": "38",
  "developer": "DAFAMLAND",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 6,
  "jml_odp": "2",
  "status_ftth": "Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "PERUMAHAN JATAYU RESIDENCE",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "Panjang Wetan, Pekalongan Utara, Kota Pekalongan, Jawa Tengah 51141",
  "stat": "Prospect",
  "potensi_hh": "85",
  "jumlah_huni": "35",
  "developer": "DAFAMLAND",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 7,
  "jml_odp": "2",
  "status_ftth": "Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "HUNIAN ISLAMI AR RAYYAN",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "jl gamer pekalongan jawa tengah",
  "stat": "Pra Prospect",
  "potensi_hh": "22",
  "jumlah_huni": "14",
  "developer": "",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 8,
  "jml_odp": "1",
  "status_ftth": "Not_Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "SAPPHIRE TOWN HOUSE",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Infrastruktur",
  "alamat": "",
  "stat": "Pra Prospect",
  "potensi_hh": "94",
  "jumlah_huni": "4",
  "developer": "",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 9,
  "jml_odp": "2",
  "status_ftth": "Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "PERUMAHAN PISMA GARDEN RESIDENCE",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "",
  "stat": "Pra Prospect",
  "potensi_hh": "107",
  "jumlah_huni": "91",
  "developer": "PT PISMA GAJAH PUTRA",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 10,
  "jml_odp": "2",
  "status_ftth": "Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "PURI SIDOMUKTI PEKALONGAN",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "jl raya bumirejo pekalongan jawa tengah",
  "stat": "Pra Prospect",
  "potensi_hh": "84",
  "jumlah_huni": "38",
  "developer": "",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 11,
  "jml_odp": "1",
  "status_ftth": "Not_Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "SHAPPIRE TOWNHOUSE PEKALONGAN",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "Jl TRUNTUM KRAPYAK KIDU PEKALONGAN JAWA TENGAH",
  "stat": "Prospect",
  "potensi_hh": "96",
  "jumlah_huni": "15",
  "developer": "PT. MITRA SHAPPIRE SEJAHTERA",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 12,
  "jml_odp": "",
  "status_ftth": "Not_Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "PERUMAHAN MUTIARA ASRI BATANG",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "jl mayjend sutoyo batang",
  "stat": "Pra Prospect",
  "potensi_hh": "100",
  "jumlah_huni": "64",
  "developer": "PT. MUTIARA KASIH",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 13,
  "jml_odp": "",
  "status_ftth": "Not_Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "PERUMAHAN MUTIARA PERMAI",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "jl mayjend sutoyo batang",
  "stat": "Pra Prospect",
  "potensi_hh": "40",
  "jumlah_huni": "18",
  "developer": "PT. MUTIARA KASIH",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 14,
  "jml_odp": "",
  "status_ftth": "Not_Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "SINGOKERTEN RESIDENCE BATANG",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "Jl Tentara Pelajar - Kauman Batang - Jawa Tengah",
  "stat": "Pra Prospect",
  "potensi_hh": "60",
  "jumlah_huni": "34",
  "developer": "",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 15,
  "jml_odp": "",
  "status_ftth": "Not_Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "KAUMAN RESIDENCE BATANG",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "Jl. Tentara Pelajar, Kadilangu, Kauman, Kec. Batang, Kabupaten Batang, Jawa Tengah 51216",
  "stat": "Go Live",
  "potensi_hh": "24",
  "jumlah_huni": "4",
  "developer": "PT. DEVARATA",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 16,
  "jml_odp": "",
  "status_ftth": "Not_Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "VILLA EXIST SEMPURNA",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Marketing",
  "alamat": "jl pemuda batang jawa tengah",
  "stat": "Go Live",
  "potensi_hh": "62",
  "jumlah_huni": "2",
  "developer": "PT GAJAHMADA BANGUN NUSANTARA",
  "nama_mitra": "Telkom Akses, PT",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 17,
  "jml_odp": "",
  "status_ftth": "Not_Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "PRIMA GARDEN 2",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Marketing",
  "alamat": "",
  "stat": "Pra Prospect",
  "potensi_hh": "118",
  "jumlah_huni": "0",
  "developer": "",
  "nama_mitra": "",
  "status_bangunan": "Siap Huni",
  "coordinate": 18,
  "jml_odp": "",
  "status_ftth": "Not_Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "TAMAN CEMARA INDAH",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Marketing",
  "alamat": "Jl Kusuma Bangsa Panjang Baru Kota Pekalongan Jawa Tengah",
  "stat": "Prospect",
  "potensi_hh": "220",
  "jumlah_huni": "2",
  "developer": "PT. INTAN KHARISMA JAYA",
  "nama_mitra": "Telkom Akses, PT",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 19,
  "jml_odp": "2",
  "status_ftth": "Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "GRAND BALE AGUNG PEKALONGAN",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "jl pangeran antasari gamer pekalongan jawa tengah",
  "stat": "Pra Prospect",
  "potensi_hh": "59",
  "jumlah_huni": "15",
  "developer": "",
  "nama_mitra": "",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 20,
  "jml_odp": "1",
  "status_ftth": "Not_Ready",
  "image": ""
 },
 {
  "sales_id": "1",
  "nama_lop": "PRIMA GARDEN ASRI",
  "nama_segment": "Premium Cluster APC",
  "nama_kemitraan": "Non Partnership",
  "alamat": "Jl sultan agung batang jawa tengah",
  "stat": "Go Live",
  "potensi_hh": "96",
  "jumlah_huni": "20",
  "developer": "PRIMA PERKASA PRATAMA",
  "nama_mitra": "Telkom Akses, PT",
  "status_bangunan": "Occupied(Sudah dihuni)",
  "coordinate": 21,
  "jml_odp": "6",
  "status_ftth": "Ready",
  "image": ""
 }
]